version: '3.8'

services:
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 443:443
    expose:
      - "443"
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  postgre:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - nesjs-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  nesjs-network: