version: '3.8'

services:
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 443:443
    expose:
      - "443"
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    networks:
      - nestjs-network
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - nestjs-network
    ports:
      - "8080:80"
networks:
  nestjs-network:
    driver: bridge