version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=jbarette
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    volumes:
      - ./back/postgres:/data/postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - nestjs-network
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.0
    build:
      context: ./back
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    restart: always
    depends_on:
      - db
  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - 8080:8080
    restart: always
    networks:
      - nestjs-network
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:
      - ./front/nginx/conf/:/etc/nginx/conf.d/
      - ./front/nginx/ssl/certs/:/etc/ssl/certs/
      - ./front/nginx/ssl/private/:/etc/ssl/private/
      - ./front/angular:/var/www/html/src

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres: