version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/data/postgres
      - POSTGRES_DB=test_db
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - nestjs-network
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 443:443
    expose:
      - "443"
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - db
  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - 8080:8080
    restart: always
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres: