version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
  nestjs:
    container_name: nestjs
    image: nestjs:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 443:443
    expose:
      - "443"
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeremy.barette@outlook.fr
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    ports:
      - "8080:80"
networks:
  nestjs-network:
    driver: bridge
volumes:
  pgdata:
  pgadmin-data: